### ISSUE TITLE
NullPointerException after AddTable

### ISSUE THREAD

**Issue by joaocarlos86** [kbastani/pinot-wikipedia-event-stream#1]
# NullPointerException after AddTable

## Steps to reproduce: 

1. Run `docker-compose up`
2. Run `docker cp ./pinot pinot-wikipedia-event-stream_pinot_1:.`
3. Run 
```bash
docker exec pinot-wikipedia-event-stream_pinot_1 bin/pinot-admin.sh AddTable \
  -tableConfigFile /pinot/wiki-table-definition.json \
  -schemaFile /pinot/wiki-schema-definition.json \
  -exec
```

## Expected

Table is created and the user can query data from that table.

## Actual

NullPointerException is being thrown by pinot's container

```
After that I started to see some errors in the container's log, such as:
`pinot_1              | Caught exception while transforming the record: {
pinot_1              |   "nullValueFields" : [ "dateTime", "parsedComment", "domain", "uri", "uuid", "changeLength" ],
pinot_1              |   "fieldToValueMap" : {
pinot_1              |     "dateTime" : "",
pinot_1              |     "parsedComment" : "",
pinot_1              |     "wiki" : "enwiki",
pinot_1              |     "title" : "Paravai Muniyamma",
pinot_1              |     "type" : "edit",
pinot_1              |     "uri" : "",
pinot_1              |     "uuid" : "",
pinot_1              |     "changeLength" : 0,
pinot_1              |     "domain" : "",
pinot_1              |     "comment" : "",
pinot_1              |     "id" : 1261283102,
pinot_1              |     "changedTime" : null,
pinot_1              |     "category" : "Category:Indian women comedians",
pinot_1              |     "user" : "100.37.165.187"
pinot_1              |   }
pinot_1              | }
pinot_1              | java.lang.NullPointerException: null
pinot_1              |  at org.apache.pinot.core.data.recordtransformer.DataTypeTransformer.transform(DataTypeTransformer.java:93) ~[pinot-all-0.4.0-SNAPSHOT-jar-with-dependencies.jar:0.4.0-SNAPSHOT-aa0a5f144ae360ef447dea01c5cc949e1b327989]
pinot_1              |  at org.apache.pinot.core.data.recordtransformer.CompositeTransformer.transform(CompositeTransformer.java:70) ~[pinot-all-0.4.0-SNAPSHOT-jar-with-dependencies.jar:0.4.0-SNAPSHOT-aa0a5f144ae360ef447dea01c5cc949e1b327989]
pinot_1              |  at org.apache.pinot.core.data.manager.realtime.LLRealtimeSegmentDataManager.processStreamEvents(LLRealtimeSegmentDataManager.java:467) [pinot-all-0.4.0-SNAPSHOT-jar-with-dependencies.jar:0.4.0-SNAPSHOT-aa0a5f144ae360ef447dea01c5cc949e1b327989]
pinot_1              |  at org.apache.pinot.core.data.manager.realtime.LLRealtimeSegmentDataManager.consumeLoop(LLRealtimeSegmentDataManager.java:395) [pinot-all-0.4.0-SNAPSHOT-jar-with-dependencies.jar:0.4.0-SNAPSHOT-aa0a5f144ae360ef447dea01c5cc949e1b327989]
pinot_1              |  at org.apache.pinot.core.data.manager.realtime.LLRealtimeSegmentDataManager$PartitionConsumer.run(LLRealtimeSegmentDataManager.java:514) [pinot-all-0.4.0-SNAPSHOT-jar-with-dependencies.jar:0.4.0-SNAPSHOT-aa0a5f144ae360ef447dea01c5cc949e1b327989]
pinot_1              |  at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

I think the problem is the field "changedTime" setted as null, I did an investigation in the code and, after changing io.example.schema.category.CategoryChange.create to use `new Date().getTime()` if `recentChange.getMeta().getDt().getTime()` is null, I got everything working. Thanks for sharing this repo!

**Comment by kbastani** [comment]
This should be fixed. Can you give it another try? Pull down the latest source and use `docker-compose down` to remove the containers and repeat the steps. I just pushed out an update to the schema as well as the corresponding docker container for the Wikipedia event stream.

**Comment by joaocarlos86** [comment]
Brilliant! Thanks for the quick response. I can confirm that it works like a charm.
